---
server:
    install: '1'
    packages: [vim, htop, iotop]
    timezone: UTC
    locale: en_US.UTF-8
vagrant_local:
    install: '1'
    vm: { base_box: trusty64, hostname: default, ip: 192.168.33.100, sharedfolder: ./, enableWindows: '1', useVagrantCloud: '1', syncType: nfs }
nginx:
    install: '0'
    docroot: /vagrant
    servername: myApp.vb
apache:
    install: '1'
    docroot: /vagrant/toran/web
    servername: toranproxy.local
mysql:
    install: '0'
    root_password: password
    database: db
    user: user
    password: password
    dump: ''
php:
    install: '1'
    ppa: php5-5.6
    packages: [php5-cli, php5-intl, php5-mcrypt, php5-mysql]
xdebug:
    install: '1'
blackfire:
    install: '0'
    server_id: 804f8ca2-0537-45b8-9a5c-418cfd890e3e
    server_token: de99ca477a765443e1290865533f70febc3d1906853bfcfbee2f6999615b5a75
